### ISSUE TITLE
Does not work with Kirby 2.2

### ISSUE THREAD

**Issue by aguynamedirvin** [helllicht/kirby-autoid#1]
The plugin doesn't seem to be compatible with the latest release of Kirby. The front end works fine but when I go to the panel and click edit on the page that will be using AutoID I get the following error: 

Fatal error: Cannot redeclare class AutoIdPlugin in /Applications/MAMP/htdocs/kirby-copy/site/fields/autoid/autoid.php on line 13

I would really love to use this plugin. Thanks!

**Comment by helllicht** [comment]
Please find the solution here: https://forum.getkirby.com/t/autoid-plugin-create-unique-page-ids/2494/5
