### ISSUE TITLE
Doesnt seem to work with Kirby 2.5.9

### ISSUE THREAD

**Issue by HashandSalt** [helllicht/kirby-autoid#10]
That's about it really. AutoID fields come up blank on Kirby 2.5.9.

**Comment by Targoran** [comment]
@HashandSalt Just tried it in Kirby 2.5.10 – can't reproduce the problem, seems to work fine. Has it worked before updating to 2.5.9? 

And could you describe the steps taken to get to the result you got? What do mean with "comes up blank"?

Please keep in mind that Kirby only updates the autoid field if you either hit _save_ or if you create a _new page_ with the autoid field in the blueprint.

**Comment by HashandSalt** [comment]
@Targoran It was an issue to do with sorting that came up in 2.5.9 and was resolved in 2.5.10. AutoID works fine now 👍
